"""empty message

Revision ID: 483ecbcfb252
Revises: fbfad8711c73
Create Date: 2018-09-10 14:35:30.484474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483ecbcfb252'
down_revision = 'fbfad8711c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption', sa.Column('employeeId', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumption', 'employeeId')
    # ### end Alembic commands ###
