"""empty message

Revision ID: fbfad8711c73
Revises: 
Create Date: 2018-09-10 14:00:25.837928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfad8711c73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeeLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=True),
    sa.Column('employeeName', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employeeLog')
    # ### end Alembic commands ###
